const img = [
  'https://images.pexels.com/photos/29502969/pexels-photo-29502969.jpeg?auto=compress&cs=tinysrgb&w=900',
  'https://images.pexels.com/photos/36823005/pexels-photo-36823005.jpeg?auto=compress&cs=tinysrgb&w=900',
  'https://images.pexels.com/photos/10907855/pexels-photo-10907855.jpeg?auto=compress&cs=tinysrgb&w=900',
  'https://images.pexels.com/photos/29502932/pexels-photo-29502932.jpeg?auto=compress&cs=tinysrgb&w=900',
  'https://images.pexels.com/photos/29502912/pexels-photo-29502912.jpeg?auto=compress&cs=tinysrgb&w=900',
  'https://images.pexels.com/photos/21235147/pexels-photo-21235147.jpeg?auto=compress&cs=tinysrgb&w=900',
  'https://images.pexels.com/photos/6256046/pexels-photo-6256046.jpeg?auto=compress&cs=tinysrgb&w=900',
  'https://images.pexels.com/photos/19373665/pexels-photo-19373665.jpeg?auto=compress&cs=tinysrgb&w=900',
  'https://images.pexels.com/photos/37601638/pexels-photo-37601638.jpeg?auto=compress&cs=tinysrgb&w=900',
  'https://images.pexels.com/photos/30200528/pexels-photo-30200528.jpeg?auto=compress&cs=tinysrgb&w=900',
];

const seedRaw: [string, string, string, number, string][] = [
  ['The Quiet Hoop', 'Earrings', 'Minimal', 899, 'Women'],
  ['Mogra Pearl Drops', 'Earrings', 'Traditional', 1199, 'Women'],
  ['Everyday Gold Studs', 'Second Studs', 'Anti-Tarnish', 499, 'Women'],
  ['Meera Textured Ring', 'Rings', 'Everyday', 1299, 'Women'],
  ['Sona Layered Chain', 'Necklaces', 'New Arrivals', 1799, 'Women'],
  ['Aara Cuff Bracelet', 'Bracelets', 'Everyday', 1499, 'Women'],
  ['Luna Shell Hoops', 'Earrings', 'Minimal', 999, 'Women'],
  ['Nila Signet Ring', 'Rings', 'Best Sellers', 1499, 'Unisex'],
  ['Maya Mini Hoops', 'Earrings', 'Anti-Tarnish', 799, 'Women'],
  ['Kairi Pendant', 'Necklaces', 'Everyday', 1599, 'Women'],
  ['Tara Second Studs', 'Second Studs', 'Minimal', 399, 'Women'],
  ['Anaya Dome Earrings', 'Earrings', 'New Arrivals', 1699, 'Women'],
  ['Ira Everyday Chain', 'Chains', 'Everyday', 1899, 'Unisex'],
  ['Vanya Open Ring', 'Rings', 'Minimal', 1199, 'Women'],
  ['Ruh Gold Bracelet', 'Bracelets', 'Best Sellers', 1399, 'Unisex'],
  ['Aria Pearl Pendant', 'Necklaces', 'Bridal', 1999, 'Women'],
  ['Dev Minimal Chain', 'Chains', "Men's", 2299, 'Men'],
  ['Riva Sculptural Hoops', 'Earrings', 'Festive', 1299, 'Women'],
  ['Kavya Nose Pin', 'Nose Pins', 'Anti-Tarnish', 599, 'Women'],
  ['Asha Temple Drops', 'Earrings', 'Traditional', 1899, 'Women'],
  ['Nava Stack Ring', 'Rings', 'Festive', 1599, 'Women'],
  ['Riz Classic Cuff', 'Bracelets', "Men's", 1199, 'Men'],
  ['Aadi Signet', 'Rings', "Men's", 2499, 'Men'],
  ['Suhana Chandbali', 'Earrings', 'Bridal', 2199, 'Women'],
  ['Kaveri Anklet', 'Anklets', 'Everyday', 999, 'Women'],
  ['Nila Gift Set', 'Jewellery Sets', 'Festive', 2699, 'Women'],
  ['Little Mogra Studs', 'Kids Jewellery', 'Kids', 699, 'Kids'],
  ['Little Riz Bracelet', 'Kids Jewellery', 'Kids', 799, 'Kids'],
  ['Tiny Star Chain', 'Kids Jewellery', 'Kids', 899, 'Kids'],
  ['Muthu Bridal Set', 'Jewellery Sets', 'Bridal', 4999, 'Women'],
  ['Kasavu Jhumka', 'Earrings', 'Traditional', 2399, 'Women'],
  ['Malabar Choker', 'Necklaces', 'Traditional', 3299, 'Women'],
  ['Kerala Bloom Bangle', 'Bracelets', 'Festive', 1799, 'Women'],
  ['Matte Link Chain', 'Chains', "Men's", 1999, 'Men'],
  ['Aranya Pendant', 'Necklaces', 'Minimal', 1399, 'Unisex'],
  ['Sia Limited Drops', 'Earrings', 'Festive', 2899, 'Women'],
  ['Riz Mini Hoops', 'Earrings', 'New Arrivals', 1099, 'Women'],
  ['Veda Bridal Necklace', 'Necklaces', 'Bridal', 3999, 'Women'],
  ['Tiny Moon Gift Set', 'Jewellery Sets', 'Kids', 1299, 'Kids'],
  ['Kochi Classic Anklet', 'Anklets', 'Anti-Tarnish', 1199, 'Women'],
];

export const INITIAL_PRODUCTS = seedRaw.map(([name, category, collection, price, gender], i) => {
  const newArrival = collection === 'New Arrivals' || i > 35;
  const bestseller = collection === 'Best Sellers' || i % 7 === 0;
  const originalPrice = i % 4 === 0 ? price + 400 : undefined;
  return {
    name,
    category,
    collection,
    price,
    originalPrice,
    gender,
    images: [img[i % img.length], img[(i + 3) % img.length], img[(i + 5) % img.length]],
    description: 'A considered piece for days that call for a little more glow. Light enough to live in, distinctive enough to be remembered.',
    material: i % 2 === 0 ? '925 Silver' : 'Brass with Premium Alloy',
    finish: '18K Gold Vermeil',
    stock: i === 18 ? 0 : 12 + i,
    colors: ['Gold', 'Rose Gold', 'Silver'],
    featured: i < 10,
    bestseller,
    newArrival,
  };
});
